# Generated by Django 2.2.16 on 2020-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HGgfkhjfkhg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgjhggjgjhg', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
