# Generated by Django 2.2.16 on 2020-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_hggfkhjfkhg"),
    ]

    operations = [
        migrations.AddField(
            model_name="hggfkhjfkhg",
            name="hgfhgfhgf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
