# Generated by Django 2.2.16 on 2020-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hggfkhjfkhg_hgfhgfhgf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hggfkhjfkhg',
            name='cvnbdfgbvc',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
